# Generated by Django 2.2.5 on 2021-08-27 17:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('is_company', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('intern_name', models.CharField(default='', max_length=200)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('hire', models.CharField(default='', max_length=200)),
                ('available', models.CharField(default='', max_length=200)),
                ('job_title', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_office_location', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
                ('college_name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('basic_skills', models.TextField(default='')),
                ('city', models.CharField(default='', max_length=200)),
                ('year_of_study', models.IntegerField(choices=[(1, 'first_year'), (2, 'second_year'), (3, 'third_year'), (4, 'fourth_year')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_duration', models.IntegerField(default=1)),
                ('job_content', models.TextField()),
                ('job_published', models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 29, 15, 505180), verbose_name='date published')),
                ('job_stipend', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category')),
                ('company', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Company')),
                ('location', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire', models.CharField(default='', max_length=200)),
                ('available', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to='documents/')),
                ('is_accept', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Job')),
            ],
        ),
    ]
