# Generated by Django 2.2.5 on 2019-09-18 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='job_title',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 18, 20, 42, 54, 1438), verbose_name='date published'),
        ),
    ]
