# Generated by Django 2.2.5 on 2020-01-01 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 16, 37, 54, 966293), verbose_name='date published'),
        ),
    ]
