# Generated by Django 2.2.5 on 2019-09-28 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intern',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 12, 21, 2, 440449), verbose_name='date published'),
        ),
    ]
