# Generated by Django 2.2.5 on 2021-08-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password2',
            new_name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 33, 11, 578550), verbose_name='date published'),
        ),
    ]
