# Generated by Django 2.2.4 on 2019-09-25 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='intern_college',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 14, 53, 48, 972943), verbose_name='date published'),
        ),
    ]
