# Generated by Django 2.2.5 on 2020-01-03 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 14, 31, 15, 644172), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'first_year'), (2, 'second_year'), (3, 'third_year'), (4, 'fourth_year')]),
        ),
    ]
