# Generated by Django 2.2.5 on 2019-09-16 13:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190916_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='first_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 19, 22, 58, 279608), verbose_name='date published'),
        ),
    ]
