# Generated by Django 2.2.5 on 2020-01-11 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200111_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 1, 34, 5, 371976), verbose_name='date published'),
        ),
    ]
