# Generated by Django 2.2.4 on 2019-09-14 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190914_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 20, 25, 44, 432518), verbose_name='date published'),
        ),
    ]
