# Generated by Django 2.2.4 on 2019-09-11 17:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190910_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_p', models.CharField(max_length=100)),
                ('skill_p', models.CharField(max_length=500)),
                ('college_p', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('location_p', models.CharField(max_length=100)),
                ('company_p', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skillcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_s', models.CharField(max_length=100)),
                ('Organization', models.CharField(max_length=100)),
                ('location_s', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('last_date', models.DateField()),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 11, 23, 18, 56, 77119), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intership_p',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.skillcategory'),
        ),
    ]
