# Generated by Django 2.2.5 on 2019-09-28 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190928_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('intern_name', models.CharField(default='', max_length=200)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('hire', models.CharField(default='', max_length=200)),
                ('available', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='intern',
            name='is_accept',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='is_reject',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 13, 42, 7, 431485), verbose_name='date published'),
        ),
    ]
