# Generated by Django 2.2.5 on 2021-08-27 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210827_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='head_office_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 56, 3, 528), verbose_name='date published'),
        ),
    ]
