# Generated by Django 2.2.4 on 2019-09-15 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190915_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stipend',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 23, 6, 11, 569121), verbose_name='date published'),
        ),
    ]
