# Generated by Django 2.2.4 on 2019-09-11 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190911_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('Start_date', models.DateField()),
                ('Duration', models.CharField(max_length=10)),
                ('Stipend', models.CharField(max_length=10)),
                ('Posted_On', models.DateField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 1, 16, 54, 701972), verbose_name='date published'),
        ),
    ]
