# Generated by Django 2.2.4 on 2019-09-25 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190925_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='available',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intern',
            name='hire',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 15, 50, 54, 241571), verbose_name='date published'),
        ),
    ]
