# Generated by Django 2.2.5 on 2019-09-28 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190928_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 13, 57, 47, 465524), verbose_name='date published'),
        ),
    ]
