# Generated by Django 2.2.4 on 2019-09-17 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190917_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 12, 28, 36, 110673), verbose_name='date published'),
        ),
    ]
