# Generated by Django 2.2.4 on 2019-09-21 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190920_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 21, 23, 25, 28, 352546), verbose_name='date published'),
        ),
    ]
