# Generated by Django 2.2.5 on 2021-08-28 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210828_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 5, 49, 5, 477762), verbose_name='date published'),
        ),
    ]
