# Generated by Django 2.2.5 on 2019-09-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190916_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='username',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 21, 3, 50, 657273), verbose_name='date published'),
        ),
    ]
