# Generated by Django 2.2.5 on 2019-09-28 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190928_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intern',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 14, 48, 11, 382028), verbose_name='date published'),
        ),
    ]
