# Generated by Django 2.2.4 on 2019-09-25 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190925_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 17, 22, 25, 284190), verbose_name='date published'),
        ),
    ]
