# Generated by Django 2.2.4 on 2019-09-22 08:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190922_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 14, 15, 9, 555006), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Education_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('performance_scale', models.IntegerField()),
                ('steam', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('Add_Education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Add_Education')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
