# Generated by Django 2.2.5 on 2019-09-28 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190928_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 14, 49, 0, 724675), verbose_name='date published'),
        ),
    ]
