# Generated by Django 2.2.4 on 2019-09-25 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190925_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 23, 12, 39, 489892), verbose_name='date published'),
        ),
    ]
