# Generated by Django 2.2.5 on 2021-08-28 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210828_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 28, 15, 36, 8, 227210), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
