# Generated by Django 2.2.4 on 2019-09-14 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190914_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 22, 45, 52, 420884), verbose_name='date published'),
        ),
    ]
