# Generated by Django 2.2.5 on 2019-09-16 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190916_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 21, 4, 1, 237250), verbose_name='date published'),
        ),
    ]
