# Generated by Django 2.2.4 on 2019-09-22 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190922_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='company_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 23, 18, 58, 143889), verbose_name='date published'),
        ),
    ]
