# Generated by Django 2.2.5 on 2019-09-21 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190922_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 0, 3, 19, 599152), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
