# Generated by Django 2.2.4 on 2019-09-25 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190925_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='phone_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 23, 34, 55, 609318), verbose_name='date published'),
        ),
    ]
