# Generated by Django 2.2.5 on 2019-09-29 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190928_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 8, 38, 0, 903094), verbose_name='date published'),
        ),
    ]
