# Generated by Django 2.2.5 on 2020-01-14 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200114_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 21, 36, 28, 56663), verbose_name='date published'),
        ),
    ]
