# Generated by Django 2.2.4 on 2019-09-22 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190922_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='company_id',
        ),
        migrations.AddField(
            model_name='intern',
            name='company_name',
            field=models.CharField(default='Job.user', max_length=100),
        ),
        migrations.AddField(
            model_name='intern',
            name='job_id',
            field=models.CharField(default='Job.id', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 0, 18, 56, 99801), verbose_name='date published'),
        ),
    ]
