# Generated by Django 2.2.4 on 2019-09-25 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190925_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='jobintern',
            field=models.OneToOneField(default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 25, 51, 313078), verbose_name='date published'),
        ),
    ]
