# Generated by Django 2.2.5 on 2020-01-14 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200114_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 21, 36, 33, 663466), verbose_name='date published'),
        ),
    ]
