# Generated by Django 2.2.5 on 2019-09-16 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190916_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='first_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 21, 17, 2, 561161), verbose_name='date published'),
        ),
    ]
