# Generated by Django 2.2.5 on 2019-09-22 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190922_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 7, 24, 17, 249221), verbose_name='date published'),
        ),
    ]
