# Generated by Django 2.2.4 on 2019-09-12 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190912_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile_m',
            new_name='internship',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='college_p',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='company_p',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location_p',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name_p',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skill_p',
            new_name='skill',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 20, 52, 57, 525073), verbose_name='date published'),
        ),
    ]
