# Generated by Django 2.2.4 on 2019-09-25 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190926_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='jobintern',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 30, 31, 929031), verbose_name='date published'),
        ),
    ]
