# Generated by Django 2.2.4 on 2019-09-13 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190912_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=10)),
                ('Name', models.CharField(default=None, max_length=10)),
                ('College', models.CharField(default=None, max_length=10)),
                ('Skill', models.CharField(default=None, max_length=10)),
                ('phone_no', models.CharField(default=None, max_length=10)),
                ('field', models.CharField(default=None, max_length=30)),
                ('first_n', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='skillcategory',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='field',
        ),
        migrations.AddField(
            model_name='internship',
            name='Posted_On',
            field=models.DateField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 0, 26, 46, 836364), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='type_of_field',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.internship'),
        ),
        migrations.AddField(
            model_name='student',
            name='get_intership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type_of_field'),
        ),
    ]
