# Generated by Django 2.2.5 on 2019-09-22 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190922_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 11, 23, 53, 733400), verbose_name='date published'),
        ),
    ]
