# Generated by Django 2.2.5 on 2019-09-22 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190922_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='id_job',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Id', to='main.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='id_job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intern',
            name='job_title',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Title', to='main.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 18, 10, 13, 880327), verbose_name='date published'),
        ),
    ]
