# Generated by Django 2.2.5 on 2019-09-17 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190917_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 22, 47, 39, 796549), verbose_name='date published'),
        ),
    ]
