# Generated by Django 2.2.5 on 2019-09-23 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190923_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='resume',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 21, 16, 35, 466360), verbose_name='date published'),
        ),
    ]
