# Generated by Django 2.2.5 on 2019-09-23 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190923_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='resume',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 22, 35, 22, 13400), verbose_name='date published'),
        ),
    ]
