# Generated by Django 2.2.5 on 2019-09-24 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190923_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 13, 23, 12, 997135), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', help_text='Required', max_length=200, unique=True),
        ),
    ]
