# Generated by Django 2.2.5 on 2019-09-24 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190924_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 13, 24, 53, 744961), verbose_name='date published'),
        ),
    ]
