# Generated by Django 2.2.5 on 2019-09-24 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190924_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='resume',
        ),
        migrations.AlterField(
            model_name='intern',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='intern',
            name='job_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 24, 19, 48, 34, 234602), verbose_name='date published'),
        ),
    ]
