# Generated by Django 2.2.5 on 2019-09-26 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190924_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='intern_city',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='intern_college',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='intern_skills',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='intern_study_year',
        ),
        migrations.AddField(
            model_name='intern',
            name='available',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intern',
            name='document',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='intern',
            name='hire',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='intern',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 26, 18, 35, 39, 693502), verbose_name='date published'),
        ),
    ]
